org: muratkerem
app: appsyncmasterclass-backend
service: appsyncmasterclass-backend
frameworkVersion: '2'

# [4.1] exclude `package.json` files from being bundled.
plugins:
  - serverless-appsync-plugin
  - serverless-iam-roles-per-function

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  # any env var defined here applies to all the functions
  environment:
    # (4.4.2) when using aws nodeJs SDK, always enable HTTP keep-alive
    STAGE: ${self:custom.stage}   # stage: dev # if not specified, defaults to dev
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"

package:
  exclude:
    - package-lock.json
    - package.json

custom:
  # (4.4.0) Environment is dev, unless we pass in a stage override; npm run sls -- -s prod
  stage: ${opt:stage, self:provider.stage}
  # [4.1] Create a separate `serverless.appsync-api.yml` file for AppSync configuration. 
  appSync:
    - ${file(serverless.appsync-api.yml)}

# (4.4.1) Add a functions block for the lambda trigger function
functions:
  confirmUserSignup:
    handler: functions/confirm-user-signup.handler
    # the function needs to know the name of the UsersTable, which is generated by CloudFormation
    # this one is a function level env var, they aggregate over provider: environment:
    environment:
      USERS_TABLE: !Ref UsersTable
    # the function needs the permission to write to the UsersTable
    # note: we don't want a global iamRoleStatements: under provider: , we just want permission for this function
    # (4.4.2) we use npm i -D serverless-iam-roles-per-function to do this
    iamRoleStatements:
      - Effect: Allow
        Action: dynamodb:PutItem
        Resource: !GetAtt UsersTable.Arn

resources:
  Resources:
    # [4.4] Save user profile on PostConfirmation
    # (4.4.0) Create a DynamoDB table to store user profiles
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S # string
        Tags:
          - Key: Environment
            # (4.4.0) Environment is dev, unless we pass in a stage override; npm run sls -- -s prod
            Value: ${self:custom.stage}
            # a helper tag to aid in monitoring the individual cost of dynamodb tables
          - Key: Name
            Value: users-table
  
    # [4.3] Configure Cognito User Pool
    CognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        AutoVerifiedAttributes:
          - email
        Policies:
          PasswordPolicy:
            MinimumLength: 8
            RequireLowercase: false
            RequireNumbers: false
            RequireUppercase: false
            RequireSymbols: false
        # (4.3.0) allows login via email    
        UsernameAttributes:
          - email
        # (4.3.0) we need to know the name and associate it with cognito user pool
        # with this setting we can configure a name attribute  
        Schema:
          - AttributeDataType: String
            Name: name
            Required: false
            Mutable: true
        # (4.4.3) Configure Cognito to call the lambda trigger function when a new user is registered.
        # We can't use the lambda function's name, because that's something local to serverless framework
        # instead we figure out the logical id sls generates for the lambda function, by using npm run sls -- package
        # which generates cloudformation template under .serverless folder. There look for ConfirmUserSignupLambdaFunction
        LambdaConfig:
          PostConfirmation: !GetAtt ConfirmUserSignupLambdaFunction.Arn 
    
    # (4.4.4) We also need to give Cognito additional permissions to call the lambda function, by default it doesn't have any
    # grants CognitoUserPool the lambda:invokeFunction permission for ConfirmUserSignupLambdaFunction
    UserPoolInvokeConfirmUserSignupLambdaPermission:
      Type: AWS::Lambda::Permission
      Properties:
        Action: lambda:invokeFunction
        FunctionName: !Ref ConfirmUserSignupLambdaFunction
        Principal: cognito-idp.amazonaws.com
        SourceArn: !GetAtt CognitoUserPool.Arn

    # (4.3.5) We need to be logged in with Cognito to test AppSync queries. 
    # Create a cognito user by hand at *CognitoUserPool / Users and Groups*. (I used my email).
    # We also need to configure a application client at *CognitoUserPool / App clients* 
    # to be able to interact with the Cognito User Pool. 
    # We do this by adding a resource here
    WebUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        UserPoolId: !Ref CognitoUserPool
        ClientName: web
        ExplicitAuthFlows:
          - ALLOW_USER_SRP_AUTH
          - ALLOW_USER_PASSWORD_AUTH
          - ALLOW_REFRESH_TOKEN_AUTH
        # with this we get a "wrong pw" in case a user doesn't exist, makes it harder for attackers to find out if the user exists  
        PreventUserExistenceErrors: ENABLED

  Outputs:
    # (4.3.1) We need the CognitoUserPoolId of the CognitoUserPool as a cloud formation output, 
    # We get that value with !Ref
    CognitoUserPoolId:
      Value: !Ref CognitoUserPool