name: Remove temp stack after merge

# we are triggering the workflow when a pull request is closed
# and checking if it's merged with if: github.event.pull_request.merged == true
# If it is merged, then we execute the job to remove the stack.

on:
  pull_request:
    types: [closed]

env:
  AWS_REGION: us-east-1

jobs:
  remove-stack:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update

          rm awscliv2.zip
          rm -r ./aws

      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v6

      - name: Install dependencies
        uses: cypress-io/github-action@v5.6.1
        with:
          install-command: npm ci --force
          runTests: false

      - name: Remove stack ${{ steps.branch-name.outputs.current_branch }}
        run: |
          npm run sls -- config credentials --provider aws --key ${{ secrets.AWS_ACCESS_KEY_ID }} --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }} --overwrite     
          npm run sls -- remove -s ${{ steps.branch-name.outputs.current_branch }}
